#ifndef EXT_SIM_MATRIX_HH
#define EXT_SIM_MATRIX_HH

inline int blosum62(char x, char y) {
  switch (x) {
    case 'A': switch (y) {
      case 'A': return 4;
      case 'R': return -1;
      case 'N': return -2;
      case 'D': return -2;
      case 'C': return 0;
      case 'Q': return -1;
      case 'E': return -1;
      case 'G': return 0;
      case 'H': return -2;
      case 'I': return -1;
      case 'L': return -1;
      case 'K': return -1;
      case 'M': return -1;
      case 'F': return -2;
      case 'P': return -1;
      case 'S': return 1;
      case 'T': return 0;
      case 'W': return -3;
      case 'Y': return -2;
      case 'V': return 0;
      case 'B': return -2;
      case 'Z': return -1;
      case 'X': return 0;
      default: return -4;
    } break;
    case 'R': switch (y) {
      case 'A': return -1;
      case 'R': return 5;
      case 'N': return 0;
      case 'D': return -2;
      case 'C': return -3;
      case 'Q': return 1;
      case 'E': return 0;
      case 'G': return -2;
      case 'H': return 0;
      case 'I': return -3;
      case 'L': return -2;
      case 'K': return 2;
      case 'M': return -1;
      case 'F': return -3;
      case 'P': return -2;
      case 'S': return -1;
      case 'T': return -1;
      case 'W': return -3;
      case 'Y': return -2;
      case 'V': return -3;
      case 'B': return -1;
      case 'Z': return 0;
      case 'X': return -1;
      default: return -4;
    } break;
    case 'N': switch (y) {
      case 'A': return -2;
      case 'R': return 0;
      case 'N': return 6;
      case 'D': return 1;
      case 'C': return -3;
      case 'Q': return 0;
      case 'E': return 0;
      case 'G': return 0;
      case 'H': return 1;
      case 'I': return -3;
      case 'L': return -3;
      case 'K': return 0;
      case 'M': return -2;
      case 'F': return -3;
      case 'P': return -2;
      case 'S': return 1;
      case 'T': return 0;
      case 'W': return -4;
      case 'Y': return -2;
      case 'V': return -3;
      case 'B': return 3;
      case 'Z': return 0;
      case 'X': return -1;
      default: return -4;
    } break;
    case 'D': switch (y) {
      case 'A': return -2;
      case 'R': return -2;
      case 'N': return 1;
      case 'D': return 6;
      case 'C': return -3;
      case 'Q': return 0;
      case 'E': return 2;
      case 'G': return -1;
      case 'H': return -1;
      case 'I': return -3;
      case 'L': return -4;
      case 'K': return -1;
      case 'M': return -3;
      case 'F': return -3;
      case 'P': return -1;
      case 'S': return 0;
      case 'T': return -1;
      case 'W': return -4;
      case 'Y': return -3;
      case 'V': return -3;
      case 'B': return 4;
      case 'Z': return 1;
      case 'X': return -1;
      default: return -4;
    } break;
    case 'C': switch (y) {
      case 'A': return 0;
      case 'R': return -3;
      case 'N': return -3;
      case 'D': return -3;
      case 'C': return 9;
      case 'Q': return -3;
      case 'E': return -4;
      case 'G': return -3;
      case 'H': return -3;
      case 'I': return -1;
      case 'L': return -1;
      case 'K': return -3;
      case 'M': return -1;
      case 'F': return -2;
      case 'P': return -3;
      case 'S': return -1;
      case 'T': return -1;
      case 'W': return -2;
      case 'Y': return -2;
      case 'V': return -1;
      case 'B': return -3;
      case 'Z': return -3;
      case 'X': return -2;
      default: return -4;
    } break;
    case 'Q': switch (y) {
      case 'A': return -1;
      case 'R': return 1;
      case 'N': return 0;
      case 'D': return 0;
      case 'C': return -3;
      case 'Q': return 5;
      case 'E': return 2;
      case 'G': return -2;
      case 'H': return 0;
      case 'I': return -3;
      case 'L': return -2;
      case 'K': return 1;
      case 'M': return 0;
      case 'F': return -3;
      case 'P': return -1;
      case 'S': return 0;
      case 'T': return -1;
      case 'W': return -2;
      case 'Y': return -1;
      case 'V': return -2;
      case 'B': return 0;
      case 'Z': return 3;
      case 'X': return -1;
      default: return -4;
    } break;
    case 'E': switch (y) {
      case 'A': return -1;
      case 'R': return 0;
      case 'N': return 0;
      case 'D': return 2;
      case 'C': return -4;
      case 'Q': return 2;
      case 'E': return 5;
      case 'G': return -2;
      case 'H': return 0;
      case 'I': return -3;
      case 'L': return -3;
      case 'K': return 1;
      case 'M': return -2;
      case 'F': return -3;
      case 'P': return -1;
      case 'S': return 0;
      case 'T': return -1;
      case 'W': return -3;
      case 'Y': return -2;
      case 'V': return -2;
      case 'B': return 1;
      case 'Z': return 4;
      case 'X': return -1;
      default: return -4;
    } break;
    case 'G': switch (y) {
      case 'A': return 0;
      case 'R': return -2;
      case 'N': return 0;
      case 'D': return -1;
      case 'C': return -3;
      case 'Q': return -2;
      case 'E': return -2;
      case 'G': return 6;
      case 'H': return -2;
      case 'I': return -4;
      case 'L': return -4;
      case 'K': return -2;
      case 'M': return -3;
      case 'F': return -3;
      case 'P': return -2;
      case 'S': return 0;
      case 'T': return -2;
      case 'W': return -2;
      case 'Y': return -3;
      case 'V': return -3;
      case 'B': return -1;
      case 'Z': return -2;
      case 'X': return -1;
      default: return -4;
    } break;
    case 'H': switch (y) {
      case 'A': return -2;
      case 'R': return 0;
      case 'N': return 1;
      case 'D': return -1;
      case 'C': return -3;
      case 'Q': return 0;
      case 'E': return 0;
      case 'G': return -2;
      case 'H': return 8;
      case 'I': return -3;
      case 'L': return -3;
      case 'K': return -1;
      case 'M': return -2;
      case 'F': return -1;
      case 'P': return -2;
      case 'S': return -1;
      case 'T': return -2;
      case 'W': return -2;
      case 'Y': return 2;
      case 'V': return -3;
      case 'B': return 0;
      case 'Z': return 0;
      case 'X': return -1;
      default: return -4;
    } break;
    case 'I': switch (y) {
      case 'A': return -1;
      case 'R': return -3;
      case 'N': return -3;
      case 'D': return -3;
      case 'C': return -1;
      case 'Q': return -3;
      case 'E': return -3;
      case 'G': return -4;
      case 'H': return -3;
      case 'I': return 4;
      case 'L': return 2;
      case 'K': return -3;
      case 'M': return 1;
      case 'F': return 0;
      case 'P': return -3;
      case 'S': return -2;
      case 'T': return -1;
      case 'W': return -3;
      case 'Y': return -1;
      case 'V': return 3;
      case 'B': return -3;
      case 'Z': return -3;
      case 'X': return -1;
      default: return -4;
    } break;
    case 'L': switch (y) {
      case 'A': return -1;
      case 'R': return -2;
      case 'N': return -3;
      case 'D': return -4;
      case 'C': return -1;
      case 'Q': return -2;
      case 'E': return -3;
      case 'G': return -4;
      case 'H': return -3;
      case 'I': return 2;
      case 'L': return 4;
      case 'K': return -2;
      case 'M': return 2;
      case 'F': return 0;
      case 'P': return -3;
      case 'S': return -2;
      case 'T': return -1;
      case 'W': return -2;
      case 'Y': return -1;
      case 'V': return 1;
      case 'B': return -4;
      case 'Z': return -3;
      case 'X': return -1;
      default: return -4;
    } break;
    case 'K': switch (y) {
      case 'A': return -1;
      case 'R': return 2;
      case 'N': return 0;
      case 'D': return -1;
      case 'C': return -3;
      case 'Q': return 1;
      case 'E': return 1;
      case 'G': return -2;
      case 'H': return -1;
      case 'I': return -3;
      case 'L': return -2;
      case 'K': return 5;
      case 'M': return -1;
      case 'F': return -3;
      case 'P': return -1;
      case 'S': return 0;
      case 'T': return -1;
      case 'W': return -3;
      case 'Y': return -2;
      case 'V': return -2;
      case 'B': return 0;
      case 'Z': return 1;
      case 'X': return -1;
      default: return -4;
    } break;
    case 'M': switch (y) {
      case 'A': return -1;
      case 'R': return -1;
      case 'N': return -2;
      case 'D': return -3;
      case 'C': return -1;
      case 'Q': return 0;
      case 'E': return -2;
      case 'G': return -3;
      case 'H': return -2;
      case 'I': return 1;
      case 'L': return 2;
      case 'K': return -1;
      case 'M': return 5;
      case 'F': return 0;
      case 'P': return -2;
      case 'S': return -1;
      case 'T': return -1;
      case 'W': return -1;
      case 'Y': return -1;
      case 'V': return 1;
      case 'B': return -3;
      case 'Z': return -1;
      case 'X': return -1;
      default: return -4;
    } break;
    case 'F': switch (y) {
      case 'A': return -2;
      case 'R': return -3;
      case 'N': return -3;
      case 'D': return -3;
      case 'C': return -2;
      case 'Q': return -3;
      case 'E': return -3;
      case 'G': return -3;
      case 'H': return -1;
      case 'I': return 0;
      case 'L': return 0;
      case 'K': return -3;
      case 'M': return 0;
      case 'F': return 6;
      case 'P': return -4;
      case 'S': return -2;
      case 'T': return -2;
      case 'W': return 1;
      case 'Y': return 3;
      case 'V': return -1;
      case 'B': return -3;
      case 'Z': return -3;
      case 'X': return -1;
      default: return -4;
    } break;
    case 'P': switch (y) {
      case 'A': return -1;
      case 'R': return -2;
      case 'N': return -2;
      case 'D': return -1;
      case 'C': return -3;
      case 'Q': return -1;
      case 'E': return -1;
      case 'G': return -2;
      case 'H': return -2;
      case 'I': return -3;
      case 'L': return -3;
      case 'K': return -1;
      case 'M': return -2;
      case 'F': return -4;
      case 'P': return 7;
      case 'S': return -1;
      case 'T': return -1;
      case 'W': return -4;
      case 'Y': return -3;
      case 'V': return -2;
      case 'B': return -2;
      case 'Z': return -1;
      case 'X': return -2;
      default: return -4;
    } break;
    case 'S': switch (y) {
      case 'A': return 1;
      case 'R': return -1;
      case 'N': return 1;
      case 'D': return 0;
      case 'C': return -1;
      case 'Q': return 0;
      case 'E': return 0;
      case 'G': return 0;
      case 'H': return -1;
      case 'I': return -2;
      case 'L': return -2;
      case 'K': return 0;
      case 'M': return -1;
      case 'F': return -2;
      case 'P': return -1;
      case 'S': return 4;
      case 'T': return 1;
      case 'W': return -3;
      case 'Y': return -2;
      case 'V': return -2;
      case 'B': return 0;
      case 'Z': return 0;
      case 'X': return 0;
      default: return -4;
    } break;
    case 'T': switch (y) {
      case 'A': return 0;
      case 'R': return -1;
      case 'N': return 0;
      case 'D': return -1;
      case 'C': return -1;
      case 'Q': return -1;
      case 'E': return -1;
      case 'G': return -2;
      case 'H': return -2;
      case 'I': return -1;
      case 'L': return -1;
      case 'K': return -1;
      case 'M': return -1;
      case 'F': return -2;
      case 'P': return -1;
      case 'S': return 1;
      case 'T': return 5;
      case 'W': return -2;
      case 'Y': return -2;
      case 'V': return 0;
      case 'B': return -1;
      case 'Z': return -1;
      case 'X': return 0;
      default: return -4;
    } break;
    case 'W': switch (y) {
      case 'A': return -3;
      case 'R': return -3;
      case 'N': return -4;
      case 'D': return -4;
      case 'C': return -2;
      case 'Q': return -2;
      case 'E': return -3;
      case 'G': return -2;
      case 'H': return -2;
      case 'I': return -3;
      case 'L': return -2;
      case 'K': return -3;
      case 'M': return -1;
      case 'F': return 1;
      case 'P': return -4;
      case 'S': return -3;
      case 'T': return -2;
      case 'W': return 11;
      case 'Y': return 2;
      case 'V': return -3;
      case 'B': return -4;
      case 'Z': return -3;
      case 'X': return -2;
      default: return -4;
    } break;
    case 'Y': switch (y) {
      case 'A': return -2;
      case 'R': return -2;
      case 'N': return -2;
      case 'D': return -3;
      case 'C': return -2;
      case 'Q': return -1;
      case 'E': return -2;
      case 'G': return -3;
      case 'H': return 2;
      case 'I': return -1;
      case 'L': return -1;
      case 'K': return -2;
      case 'M': return -1;
      case 'F': return 3;
      case 'P': return -3;
      case 'S': return -2;
      case 'T': return -2;
      case 'W': return 2;
      case 'Y': return 7;
      case 'V': return -1;
      case 'B': return -3;
      case 'Z': return -2;
      case 'X': return -1;
      default: return -4;
    } break;
    case 'V': switch (y) {
      case 'A': return 0;
      case 'R': return -3;
      case 'N': return -3;
      case 'D': return -3;
      case 'C': return -1;
      case 'Q': return -2;
      case 'E': return -2;
      case 'G': return -3;
      case 'H': return -3;
      case 'I': return 3;
      case 'L': return 1;
      case 'K': return -2;
      case 'M': return 1;
      case 'F': return -1;
      case 'P': return -2;
      case 'S': return -2;
      case 'T': return 0;
      case 'W': return -3;
      case 'Y': return -1;
      case 'V': return 4;
      case 'B': return -3;
      case 'Z': return -2;
      case 'X': return -1;
      default: return -4;
    } break;
    case 'B': switch (y) {
      case 'A': return -2;
      case 'R': return -1;
      case 'N': return 3;
      case 'D': return 4;
      case 'C': return -3;
      case 'Q': return 0;
      case 'E': return 1;
      case 'G': return -1;
      case 'H': return 0;
      case 'I': return -3;
      case 'L': return -4;
      case 'K': return 0;
      case 'M': return -3;
      case 'F': return -3;
      case 'P': return -2;
      case 'S': return 0;
      case 'T': return -1;
      case 'W': return -4;
      case 'Y': return -3;
      case 'V': return -3;
      case 'B': return 4;
      case 'Z': return 1;
      case 'X': return -1;
      default: return -4;
    } break;
    case 'Z': switch (y) {
      case 'A': return -1;
      case 'R': return 0;
      case 'N': return 0;
      case 'D': return 1;
      case 'C': return -3;
      case 'Q': return 3;
      case 'E': return 4;
      case 'G': return -2;
      case 'H': return 0;
      case 'I': return -3;
      case 'L': return -3;
      case 'K': return 1;
      case 'M': return -1;
      case 'F': return -3;
      case 'P': return -1;
      case 'S': return 0;
      case 'T': return -1;
      case 'W': return -3;
      case 'Y': return -2;
      case 'V': return -2;
      case 'B': return 1;
      case 'Z': return 4;
      case 'X': return -1;
      default: return -4;
    } break;
    case 'X': switch (y) {
      case 'A': return 0;
      case 'R': return -1;
      case 'N': return -1;
      case 'D': return -1;
      case 'C': return -2;
      case 'Q': return -1;
      case 'E': return -1;
      case 'G': return -1;
      case 'H': return -1;
      case 'I': return -1;
      case 'L': return -1;
      case 'K': return -1;
      case 'M': return -1;
      case 'F': return -1;
      case 'P': return -2;
      case 'S': return 0;
      case 'T': return 0;
      case 'W': return -2;
      case 'Y': return -1;
      case 'V': return -1;
      case 'B': return -1;
      case 'Z': return -1;
      case 'X': return -1;
      default: return -4;
    } break;
    default: return -4;
  }
  return -4;
}

#endif
